name: build-and-deploy
on:
  push:
    branches:
      - develop
jobs: 
  fetchandbuild:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "16.14.0"
        - run: yarn
        - run: yarn build
        - uses: JamesIves/github-pages-deploy-action@4.1.7
          with:
            branch: page
            folder: build