name: build-and-deploy
on:
  push:
    branches:
      - develop
jobs: 
  fetchandbuild:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: "16.14.0"
        - run: yarn
        - run: yarn prod
        - uses: JamesIves/github-pages-deploy-action@v4
          with:
            branch: page
            folder: build